# Scrape config for the Summary API exporter.
# This assumes that the exporter is available at kube-summary-exporter:9779
- job_name: "kubernetes-summary"
  kubernetes_sd_configs:
    - role: node
  relabel_configs:
    - source_labels: [__meta_kubernetes_node_label_role]
      action: replace
      target_label: role
    - source_labels: [__meta_kubernetes_node_name]
      regex: (.+)
      target_label: __metrics_path__
      replacement: /node/${1}
    - target_label: __address__
      replacement: kube-summary-exporter:9779
